In [1]:
import pprint
import numpy as np
np.set_printoptions(precision=3)

## 01 評価値行列の生成

In [3]:
R = np.array(
    [
        [np.nan,  4.,     3.,      1.,     2.,     np.nan],
        [5.,      5.,     4.,      np.nan, 3.,     3.],
        [4.,      np.nan, 5.,      3.,     2.,     np.nan],
        [np.nan,  3.,     np.nan,  2.,     1.,     1.],
        [2.,      1.,     2.,      4.,     np.nan, 3.],
    ]
)

In [4]:
print('R = \n{}'.format(R))

R = 
[[nan  4.  3.  1.  2. nan]
 [ 5.  5.  4. nan  3.  3.]
 [ 4. nan  5.  3.  2. nan]
 [nan  3. nan  2.  1.  1.]
 [ 2.  1.  2.  4. nan  3.]]


## 02 ユーザ集合

In [7]:
U = np.arange(R.shape[0])

In [8]:
print('U = {}'.format(U))

U = [0 1 2 3 4]


## 03 アイテム集合

In [9]:
I = np.arange(R.shape[1])

In [10]:
print('I = {}'.format(I))

I = [0 1 2 3 4 5]


## 04 ユーザ数

In [13]:
print('|U| = {}'.format(U.size))

|U| = 5


## 05 アイテム数

In [14]:
print('|I| = {}'.format(I.size))

|I| = 6


## 06 評価値

In [15]:
u = 0
i = 1
print('r{}{} = {}'.format(u, i, R[u, i]))

r01 = 4.0


## 07 評価値行列の全要素数

In [16]:
print('Rの全要素数 = {}'.format(R.size))

Rの全要素数 = 30


## 08 観測されているか否かの判定

In [20]:
print('観測値 = \n{}'.format(~np.isnan(R)))

観測値 = 
[[False  True  True  True  True False]
 [ True  True  True False  True  True]
 [ True False  True  True  True False]
 [False  True False  True  True  True]
 [ True  True  True  True False  True]]


## 09 評価値行列の観測値数

In [23]:
print('|R| = {}'.format(np.count_nonzero(~np.isnan(R))))

|R| = 22


In [28]:
R[~np.isnan(R)].size

22

## 10 評価値行列の疎性

In [32]:
sparsity = 1 - np.count_nonzero([~np.isnan(R)]) / (I.size * U.size)

In [33]:
print('sparsity = {:.3f}'.format(sparsity))

sparsity = 0.267


## 11 ユーザuが評価済みのアイテム集合

In [40]:
u = 0

print('I{} = {}'.format(u, I[~np.isnan(R[u])]))

I0 = [1 2 3 4]


## 12 各ユーザの評価済みアイテム集合

In [63]:
[I[~np.isnan(line)] for line in R]

[array([1, 2, 3, 4]),
 array([0, 1, 2, 4, 5]),
 array([0, 2, 3, 4]),
 array([1, 3, 4, 5]),
 array([0, 1, 2, 3, 5])]

## 13 ユーザuとユーザvの共通の評価済みアイテム集合

In [52]:
u = 0
v = 1

Iuv = np.intersect1d(I[~np.isnan(R[u])], I[~np.isnan(R[v])])

print('I{}{} = {}'.format(u, v, Iuv))

I01 = [1 2 4]


## 14 アイテムiを評価済みのユーザ集合

In [59]:
i = 0
print('U{} = {}'.format(i, U[~np.isnan(R[:, i])]))

U0 = [1 2 4]


## 15 各アイテムの評価済みユーザ集合

In [68]:
Ui = [U[~np.isnan(R[:, i])] for i in range(R.shape[1])]

In [69]:
print('Ui = ')
pprint.pprint(Ui)

Ui = 
[array([1, 2, 4]),
 array([0, 1, 3, 4]),
 array([0, 1, 2, 4]),
 array([0, 2, 3, 4]),
 array([0, 1, 2, 3]),
 array([1, 3, 4])]


## 16 アイテムiとアイテムjの両方を評価済みのユーザ集合

In [75]:
i = 0
j = 4

Uij = np.intersect1d(Ui[i], Ui[j])

print('U{}{} = {}'.format(i, j, Uij))

U04 = [1 2]


## 17 評価値行列全体の平均評価値

In [78]:
print('R全体の平均評価値 = {:.3f}'.format(np.nanmean(R)))

R全体の平均評価値 = 2.864


## 18 各アイテムの平均評価値

In [81]:
ri_mean = np.nanmean(R, axis=0)

print('ri_mean = {}'.format(ri_mean))

ri_mean = [3.667 3.25  3.5   2.5   2.    2.333]


## 19 各ユーザの平均評価値

In [83]:
ru_mean = np.nanmean(R, axis=1)

print('ru_mean = {}'.format(ru_mean))

ru_mean = [2.5  4.   3.5  1.75 2.4 ]


In [88]:
[line[~np.isnan(line)] for line in R]

[array([4., 3., 1., 2.]),
 array([5., 5., 4., 3., 3.]),
 array([4., 5., 3., 2.]),
 array([3., 2., 1., 1.]),
 array([2., 1., 2., 4., 3.])]

In [90]:
[sum(line[~np.isnan(line)])/len(line[~np.isnan(line)]) for line in R]

[2.5, 4.0, 3.5, 1.75, 2.4]

## 20 評価値ベクトルの形状変換

In [96]:
print('ru_mean = \n{}'.format(ru_mean.reshape(-1, 1)))

ru_mean = 
[[2.5 ]
 [4.  ]
 [3.5 ]
 [1.75]
 [2.4 ]]


## 21 平均中心化評価値行列

In [100]:
R2 = R - ru_mean.reshape(-1, 1)

print('R\' = \n{}'.format(R2))

R' = 
[[  nan  1.5   0.5  -1.5  -0.5    nan]
 [ 1.    1.    0.     nan -1.   -1.  ]
 [ 0.5    nan  1.5  -0.5  -1.5    nan]
 [  nan  1.25   nan  0.25 -0.75 -0.75]
 [-0.4  -1.4  -0.4   1.6    nan  0.6 ]]
