In [1]:
import pprint
import numpy as np

In [2]:
# 上位K件
TOP_K = 3

In [3]:
Du = np.array([
               [5, 3, +1],
               [6, 2, +1],
               [4, 1, +1],
               [8, 5, -1],
               [2, 4, -1],
               [3, 6, -1],
               [7, 6, -1],
               [4, 2, np.nan],
               [5, 1, np.nan],
               [8, 6, np.nan],
               [3, 4, np.nan],
               [4, 7, np.nan],
               [4, 4, np.nan],
])

In [4]:
I = np.arange(Du.shape[0])
print(I)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
x = Du[:,:-1]
print(x)

[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]


In [6]:
ru = Du[:,-1]
print(ru)

[ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]


In [7]:
Iu = I[~np.isnan(ru)]
print(Iu)

[0 1 2 3 4 5 6]


In [8]:
Iup = I[ru==+1]
print(Iup)

[0 1 2]


In [9]:
Iun = I[ru==-1]
print(Iun)

[3 4 5 6]


In [10]:
Iu_not = np.setdiff1d(I, Iu)
print(Iu_not)

[ 7  8  9 10 11 12]


## 01 好きなアイテム集合に含まれるアイテムの特徴ベクトルの集合

In [11]:
print('x[Iu+] = \n{}'.format(x[ru==+1]))

x[Iu+] = 
[[5. 3.]
 [6. 2.]
 [4. 1.]]


## 02 特徴ベクトルの総和

In [12]:
print('sum(x[Iu+]) = {}'.format(np.sum(x[ru==+1], axis=0)))

sum(x[Iu+]) = [15.  6.]


## 03 ユーザプロファイル

In [13]:
pu = (1 / Iup.size) * np.sum(x[ru==+1], axis=0)

print('pu = {}'.format(pu))

pu = [5. 2.]


## コサイン類似度

In [14]:
import math

def cos(pu, xi):
    """
    コサイン類似度関数：ユーザプロファイルpuとアイテムiの特徴ベクトルxiのコサイン類似度を返す。

    Parameters
    ----------
    pu : ndarray
        ユーザuのユーザプロファイル
    xi : ndarray
        アイテムiの特徴ベクトル

    Returns
    -------
    float
        コサイン類似度
    """
    # Q4
    # num = np.dot(pu, xi)
    num = np.sum(pu * xi)
    print('num = {}'.format(num))

    # Q5
    # den_u = np.linalg.norm(pu)
    den_u = np.sqrt(np.sum(pu * pu))
    print('den_u = {:.3f}'.format(den_u))

    # Q6
    den_i = np.linalg.norm(xi)
    
    cosine = num / (den_u * den_i)
    return cosine

In [15]:
u = 0
i = 7
print('cos(p{}, x{}) = {:.3f}'.format(u, i, cos(pu, x[i])))
u = 0
i = 11
print('cos(p{}, x{}) = {:.3f}'.format(u, i, cos(pu, x[i])))

num = 24.0
den_u = 5.385
cos(p0, x7) = 0.997
num = 34.0
den_u = 5.385
cos(p0, x11) = 0.783


## 推薦

## スコア関数

In [16]:
def score(u, i):
    """
    スコア関数：ユーザuのアイテムiに対するスコアを返す。

    Parameters
    ----------
    u : int
        ユーザuのID（ダミー）
    i : int
        アイテムiのID

    Returns
    -------
    float
        スコア
    """
    return cos(pu, x[i])

## 順位付け関数

In [17]:
def order(u, I):
    """
    順序付け関数：アイテム集合Iにおいて、ユーザu向けの推薦リストを返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    I : ndarray
        アイテム集合

    Returns
    -------
    list
        タプル(アイテムID: スコア)を要素にした推薦リスト
    """
    # Q7
    scores = {i:score(u, i) for i in I}
    
    print('scores = ')
    pprint.pprint(scores)
    
    # Q8
    rec_list = sorted(
        {i:score(u, i) for i in Iu_not}.items(), key=lambda x:x[1], 
        reverse=True
    )[:TOP_K]
    
    return rec_list

In [18]:
u = 0
rec_list = order(u, Iu_not)
print('rec_list = ')
for i, scr in rec_list:
    print('{}: {:.3f}'.format(i, scr))

num = 24.0
den_u = 5.385
num = 27.0
den_u = 5.385
num = 52.0
den_u = 5.385
num = 23.0
den_u = 5.385
num = 34.0
den_u = 5.385
num = 28.0
den_u = 5.385
scores = 
{7: 0.9965457582448796,
 8: 0.9832820049844603,
 9: 0.9656157585206697,
 10: 0.8541985556144386,
 11: 0.783110847498294,
 12: 0.9191450300180578}
num = 24.0
den_u = 5.385
num = 27.0
den_u = 5.385
num = 52.0
den_u = 5.385
num = 23.0
den_u = 5.385
num = 34.0
den_u = 5.385
num = 28.0
den_u = 5.385
rec_list = 
7: 0.997
8: 0.983
9: 0.966
