In [1]:
import numpy as np

## 01 評価履歴の生成

In [2]:
Du = np.array(
    [
     [ 5,  3,  1],
     [ 6,  2,  1],
     [ 4,  1,  1],
     [ 8,  5, -1],
     [ 2,  4, -1],
     [ 3,  6, -1],
     [ 7,  6, -1],
     [ 4,  2, np.nan],
     [ 5,  1, np.nan],
     [ 8,  6, np.nan],
     [ 3,  4, np.nan],
     [ 4,  7, np.nan],
     [ 4,  4, np.nan],
    ]
)
    
print('Du = \n{}'.format(Du))

Du = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]
 [ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


## 02 評価履歴の形状

In [3]:
print('Duの形状 = {}'.format(Du.shape))

Duの形状 = (13, 3)


## 03 評価履歴の行数

In [4]:
print('Duの行数 = {}'.format(Du.shape[0]))

Duの行数 = 13


In [5]:
len(Du)

13

## 04 評価履歴の列数

In [6]:
print('Duの列数 = {}'.format(Du.shape[1]))

Duの列数 = 3


## 05 評価履歴の全要素数

In [7]:
print('Duの全要素数 = {}'.format(Du.size))

Duの全要素数 = 39


## 06 アイテム集合

In [54]:
I = np.arange(Du.shape[0])

In [55]:
print('I = {}'.format(I))

I = [ 0  1  2  3  4  5  6  7  8  9 10 11 12]


## 07 アイテムの特徴ベクトルの集合

In [10]:
x = Du[:, :2]

In [11]:
print('x = \n{}'.format(x))

x = 
[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]


## 08 アイテムiの特徴ベクトル

In [12]:
i = 0
print('x{} = {}'.format(i, x[i]))

x0 = [5. 3.]


## 09 評価値集合

In [13]:
ru = Du[:, 2]

In [14]:
print('ru = {}'.format(ru))

ru = [ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]


## 10 評価値集合の形状

In [15]:
print('ruの形状 = {}'.format(ru.shape))

ruの形状 = (13,)


## 11 評価値集合の全要素数

In [16]:
print('ruの全要素数 = {}'.format(ru.size))

ruの全要素数 = 13


## 12 評価値集合の部分集合

In [17]:
i = 2
j = 5

In [23]:
print('ru{}からru{}までの評価値 = {}'.format(i, j-1, ru[i:j]))

ru2からru4までの評価値 = [ 1. -1. -1.]


## 13 評価値集合の要素の逆順

In [45]:
print('ruの逆順 = {}'.format(ru[::-1]))

ruの逆順 = [nan nan nan nan nan nan -1. -1. -1. -1.  1.  1.  1.]


## 14 アイテムiに対する評価値

In [46]:
i = 0
print('ru{} = {}'.format(i, ru[i]))

ru0 = 1.0


## 15 ユーザuが未評価であるか否かの判定

In [47]:
print('ユーザuが未評価 = {}'.format(np.isnan(ru)))

ユーザuが未評価 = [False False False False False False False  True  True  True  True  True
  True]


## 16 ユーザが評価済みであるか否かの判定

In [48]:
print('ユーザuが評価済み = {}'.format(~np.isnan(ru)))

ユーザuが評価済み = [ True  True  True  True  True  True  True False False False False False
 False]


## 17 ユーザuが評価済みのアイテム集合

In [58]:
Iu = I[~np.isnan(ru)]

In [59]:
print('ユーザuが評価済み = {}'.format(Iu))

ユーザuが評価済み = [0 1 2 3 4 5 6]


## 18 ユーザuが「好き」と評価したアイテム集合

In [60]:
Iup = I[ru == 1]

In [61]:
print('Iu+ = {}'.format(Iup))

Iu+ = [0 1 2]


## 19 ユーザuが「嫌い」と評価したアイテム集合

In [62]:
Iun = I[ru == -1]

In [63]:
print('Iu- = {}'.format(Iun))

Iu- = [3 4 5 6]


## 20 ユーザuが未評価のアイテム集合

In [65]:
Iu_not = I[np.isnan(ru)]

In [67]:
print('Iu_not = {}'.format(Iu_not))

Iu_not = [ 7  8  9 10 11 12]


In [68]:
np.setdiff1d(I, Iu)

array([ 7,  8,  9, 10, 11, 12])

## 21 訓練データ

In [70]:
DuL = Du[~np.isnan(ru)]

In [71]:
print('DuL = \n{}'.format(DuL))

DuL = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]]


## 22 訓練事例数

In [74]:
print('|DuL| = {}'.format(DuL.shape[0]))

|DuL| = 7


## 23 正事例数

In [79]:
print('|DuL+| = {}'.format(Du[ru == 1].shape[0]))

|DuL+| = 3


## 24 負事例数

In [80]:
print('|DuL-| = {}'.format(Du[ru == -1].shape[0]))

|DuL-| = 4


## 25 予測対象データ

In [82]:
DuU = Du[np.isnan(ru)]

In [83]:
print('DuU = \n{}'.format(DuU))

DuU = 
[[ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


## 26 予測対象事例数

In [84]:
print('|DuU| = {}'.format(DuU.shape[0]))

|DuU| = 6
